### ISSUE TITLE
IO Exception while loading Relationship file

### ISSUE THREAD

**Issue by absoffthewake** [IHTSDO/rf2-to-rf1-conversion#3]
I'm trying to convert the 2018 US SNOMED dataset (SnomedCT_USEditionRF2_PRODUCTION_20180901T120000Z.zip), and I'm getting an exception at the 92% complete mark. I've tried this on 2 different machines with the same result. Thanks!

Exporting RF1 to file...
91.87% complete.
Loading Inferred Relationship Hierarchy for Qualifying Relationship computation...

Process failed in 36.66 min after completing 407/443 operations.
Relationship Ids not used.
Cleaning up resources...
92.33% complete.Exception in thread "main" org.ihtsdo.snomed.rf2torf1conversion.RF1ConversionException: IO Exception while loading Relationship file: C:\Users\username\AppData\Local\Temp\1538062660686-0\sct2_Relationship_Snapshot_INT_20180901.txt
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationshipFile(GraphLoader.java:52)
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationships(GraphLoader.java:23)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.loadRelationshipHierarchy(ConversionManager.java:656)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.doRf2toRf1Conversion(ConversionManager.java:298)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.main(ConversionManager.java:204)
Caused by: java.io.IOException: Unable to read file C:\Users\username\AppData\Local\Temp\1538062660686-0\sct2_Relationship_Snapshot_INT_20180901.txt
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.getFile(GraphLoader.java:61)
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationshipFile(GraphLoader.java:31)
        ... 4 more

**Comment by absoffthewake** [comment]
Entire output:
C:\SNOMEDCONV\rf2-to-rf1-conversion-master>java -jar -Xms2g -Xmx8g  target\RF2toRF1Converter.jar  -b C:\SNOMEDCONV\SnomedCT_USEditionRF2_PRODUCTION_20180901T120000Z.zip
Initialising Database
Creating database schema
10.61% complete.
Extracting RF2 International Edition Data...
17.16% complete.
Loading US common RF2 Data...
19.19% complete.
Loading US specific RF2 Data...
35.44% complete.
Calculating RF2 snapshot...
54.85% complete.
Converting RF2 to RF1...
62.53% complete.
Skipping generation of RF1 History.  Set -h parameter if this is required (selected Editions only).
89.39% complete.
Exporting RF1 to file...
91.87% complete.
Loading Inferred Relationship Hierarchy for Qualifying Relationship computation...

Process failed in 36.66 min after completing 407/443 operations.
Relationship Ids not used.
Cleaning up resources...
92.33% complete.Exception in thread "main" org.ihtsdo.snomed.rf2torf1conversion.RF1ConversionException: IO Exception while loading Relationship file: C:\Users\username\AppData\Local\Temp\1538062660686-0\sct2_Relationship_Snapshot_INT_20180901.txt
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationshipFile(GraphLoader.java:52)
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationships(GraphLoader.java:23)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.loadRelationshipHierarchy(ConversionManager.java:656)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.doRf2toRf1Conversion(ConversionManager.java:298)
        at org.ihtsdo.snomed.rf2torf1conversion.ConversionManager.main(ConversionManager.java:204)
Caused by: java.io.IOException: Unable to read file C:\Users\username\AppData\Local\Temp\1538062660686-0\sct2_Relationship_Snapshot_INT_20180901.txt
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.getFile(GraphLoader.java:61)
        at org.ihtsdo.snomed.rf2torf1conversion.GraphLoader.loadRelationshipFile(GraphLoader.java:31)
        ... 4 more

C:\SNOMEDCONV\rf2-to-rf1-conversion-master>

**Comment by absoffthewake** [comment]
FYI, I worked around the issue by copying the sct2_Relationship_Snapshot_US1000124_20180901.txt file in the %temp%\15380XXXXXX-0\ folder the utility extracted and renaming it to sct2_Relationship_Snapshot_INT_20180901.txt
